import type { ExamArchiveType, ExamArchiveListType } from "./exam-archive.type";

// 전체 게시글 데이터
export const exam_archives_mock: ExamArchiveListType[] = [
  {
    id: 1,
    subject: "오픈소스SW개발방법및도구",
    count: 3,
    professor: "이성원",
    date: "2026.05.25",
  },
  {
    id: 2,
    subject: "자료구조",
    count: 3,
    professor: "박제만",
    date: "2026.05.20",
  },
  {
    id: 3,
    subject: "데이터베이스",
    count: 8,
    professor: "김태연",
    date: "2026.05.12",
  },
  {
    id: 4,
    subject: "데이터베이스",
    count: 4,
    professor: "이영구",
    date: "2026.05.03",
  },
  {
    id: 5,
    subject: "컴퓨터네트워크",
    count: 1,
    professor: "고한얼",
    date: "2026.04.20",
  },
  {
    id: 6,
    subject: "확률및통계학",
    count: 10,
    professor: "김성근",
    date: "2026.04.18",
  },
  {
    id: 7,
    subject: "논리회로",
    count: 5,
    professor: "정연모",
    date: "2026.04.04",
  },
];

// 게시글 데이터
export const exam_mock: ExamArchiveType[] = [
    {
    id: 1,
    subject: "운영체제",
    professor: "이성원",
    semester: "2025-1 중간고사",
    author: "홍길동",
    date: "2026-05-25",
    description: "운영체제 중간고사 기출문제 및 풀이입니다.",
    files: ["os-midterm-2025.pdf"],
  },
  {
    id: 2,
    subject: "운영체제",
    professor: "이성원",
    semester: "2025-1 기말고사",
    author: "김철수",
    date: "2026-05-20",
    description: "운영체제 기말고사 기출문제입니다.",
    files: ["os-final-2025.pdf"],
  },
  {
    id: 3,
    subject: "운영체제",
    professor: "이성원",
    semester: "2024-1 중간고사",
    author: "박지은",
    date: "2026-05-18",
    description: "2024년 운영체제 중간고사 족보입니다.",
    files: ["os-midterm-2024.pdf"],
  },

  // 자료구조 - 박재현 교수
  {
    id: 4,
    subject: "자료구조",
    professor: "박제만",
    semester: "2025-1 중간고사",
    author: "최민수",
    date: "2026-05-20",
    description: "자료구조 중간고사 기출 및 정답 정리.",
    files: ["ds-midterm-2025.pdf"],
  },
  {
    id: 5,
    subject: "자료구조",
    professor: "박제만",
    semester: "2024-2 기말고사",
    author: "이수진",
    date: "2026-05-15",
    description: "자료구조 기말고사 기출문제.",
    files: ["ds-final-2024.pdf"],
  },
  {
    id: 6,
    subject: "자료구조",
    professor: "박제만",
    semester: "퀴즈 및 과제",
    author: "정유진",
    date: "2026-05-10",
    description: "자료구조 수업 중 진행된 퀴즈와 과제 모음입니다.",
    files: ["ds-quiz-assignment.pdf"],
  },

  // 데이터베이스 - 김태연 교수
  {
    id: 7,
    subject: "데이터베이스",
    professor: "김태연",
    semester: "2025-1 중간고사",
    author: "김민준",
    date: "2026-05-12",
    description: "ERD, 정규화 중심의 중간고사 기출.",
    files: ["db-midterm-2025.pdf"],
  },
  {
    id: 8,
    subject: "데이터베이스",
    professor: "김태연",
    semester: "2025-1 기말고사",
    author: "박서연",
    date: "2026-05-08",
    description: "트랜잭션, 인덱스 관련 문제 포함.",
    files: ["db-final-2025.pdf"],
  },
  {
    id: 9,
    subject: "컴퓨터네트워크",
    professor: "이영구",
    semester: "2025-1 중간고사",
    author: "김도윤",
    date: "2026-05-03",
    description: "TCP/IP, OSI 7계층 중심 문제.",
    files: ["network-midterm-2025.pdf"],
  },
  {
    id: 10,
    subject: "컴퓨터네트워크",
    professor: "이영구",
    semester: "2024-2 기말고사",
    author: "한지민",
    date: "2026-04-28",
    description: "라우팅 프로토콜 및 혼잡 제어 문제 포함.",
    files: ["network-final-2024.pdf"],
  },
  {
    id: 11,
    subject: "컴퓨터네트워크",
    professor: "고한얼",
    semester: "2025-1 기말고사",
    author: "강하늘",
    date: "2026-04-20",
    description: "네트워크 보안 및 응용 계층 중심 문제.",
    files: ["network-final-kim.pdf"],
  },
  {
    id: 12,
    subject: "확률및통계학",
    professor: "김성근",
    semester: "중간고사 모음",
    author: "송예린",
    date: "2026-04-18",
    description: "최근 3년간 중간고사 기출 모음.",
    files: ["statistics-midterms.zip"],
  },
  {
    id: 13,
    subject: "논리회로",
    professor: "정연모",
    semester: "2024-2 기말고사",
    author: "조현우",
    date: "2026-04-04",
    description: "플립플롭, FSM 중심의 기말고사 자료.",
    files: ["logic-final-2024.pdf"],
  },
];