import type { ExamArchiveType, ExamArchiveListType } from "./exam-archive.type";

export const exam_archives_mock: ExamArchiveListType[] = [
  {
    id: 1,
    subject: "오픈소스SW개발방법및도구",
    count: 3,
    professor: "이성원",
    date: "2026.05.25",
  },
  {
    id: 2,
    subject: "자료구조",
    count: 3,
    professor: "박제만",
    date: "2026.05.20",
  },
  {
    id: 3,
    subject: "데이터베이스",
    count: 2,
    professor: "김태연",
    date: "2026.05.12",
  },
  {
    id: 4,
    subject: "데이터베이스",
    count: 2,
    professor: "이영구",
    date: "2026.05.03",
  },
  {
    id: 5,
    subject: "컴퓨터네트워크",
    count: 1,
    professor: "고한얼",
    date: "2026.04.20",
  },
  {
    id: 6,
    subject: "확률및랜덤변수",
    count: 1,
    professor: "김정근",
    date: "2026.04.18",
  },
  {
    id: 7,
    subject: "논리회로",
    count: 1,
    professor: "정연모",
    date: "2026.04.04",
  },
];

export const exam_mock: ExamArchiveType[] = [
  {
    id: 1,
    subject: "오픈소스SW개발방법및도구",
    professor: "이성원",
    semester: "2024-1",
    author: {
      studentNumber: "20230001",
      userID: "hasungjun",
    },
    date: "2026-05-25",
    description: "",
    files: [
      "24-1_오소_중간_기출.pdf",
      "24-1_오소_기말_기출.pdf",
      "24-1_오소_중간_예상문제.pdf",
      "24-1_오소_기말_예상문제.pdf",
    ],
  },
  {
    id: 2,
    subject: "오픈소스SW개발방법및도구",
    professor: "이성원",
    semester: "2023",
    author: {
      studentNumber: "20209999",
      userID: "user",
    },
    date: "2026-04-25",
    description:
      "[문제 1]\n질문에서 명확하게 요구함: (1) 위치와 (2) 목적의 명시되어야 함. Manager 역할을 수행할 node에서 init을 수행하며, worker node들이 접속할 수 있도록 cluster를 생성하고, worker node들이 cluster에 접속시 사용할 token을 생성함. Worker node 역할을 수행할 node에서 join을 수행하여, manager가 생성한 cluster로 조인을 추가함.",
    files: [],
  },
  {
    id: 3,
    subject: "오픈소스SW개발방법및도구",
    professor: "이성원",
    semester: "2022",
    author: {
      studentNumber: "20210012",
      userID: "bluebird",
    },
    date: "2025-05-05",
    description: "",
    files: ["23-1_오소_중간.pdf", "23-1_오소_중간_예상문제.pdf"],
  },
  {
    id: 4,
    subject: "자료구조",
    professor: "박제만",
    semester: "2025-1",
    author: {
      studentNumber: "20220014",
      userID: "daeun",
    },
    date: "2026-05-20",
    description: "자료구조 중간고사 기출 및 정답 정리.",
    files: ["ds-midterm-2025.pdf"],
  },
  {
    id: 5,
    subject: "자료구조",
    professor: "박제만",
    semester: "2024-2",
    author: {
      studentNumber: "20210032",
      userID: "sujilee",
    },
    date: "2026-05-15",
    description: "자료구조 기말고사 기출문제.",
    files: ["ds-final-2024.pdf"],
  },
  {
    id: 6,
    subject: "자료구조",
    professor: "박제만",
    semester: "퀴즈 및 과제",
    author: {
      studentNumber: "20220027",
      userID: "yujin",
    },
    date: "2026-05-10",
    description: "자료구조 수업 중 진행된 퀴즈와 과제 모음입니다.",
    files: ["ds-quiz-assignment.pdf"],
  },
  {
    id: 7,
    subject: "데이터베이스",
    professor: "김태연",
    semester: "2025-1",
    author: {
      studentNumber: "20230018",
      userID: "minji",
    },
    date: "2026-05-12",
    description: "ERD, 정규화 중심의 중간고사 기출.",
    files: ["db-midterm-2025.pdf"],
  },
  {
    id: 8,
    subject: "데이터베이스",
    professor: "김태연",
    semester: "2025-1",
    author: {
      studentNumber: "20220045",
      userID: "seoyun",
    },
    date: "2026-05-08",
    description: "트랜잭션, 인덱스 관련 문제 포함.",
    files: ["db-final-2025.pdf"],
  },
  {
    id: 9,
    subject: "데이터베이스",
    professor: "이영구",
    semester: "2025-1",
    author: {
      studentNumber: "20210009",
      userID: "ayoon",
    },
    date: "2026-05-03",
    description: "SQL, 정규화, 인덱스 중심 문제.",
    files: ["db-midterm-lee-2025.pdf"],
  },
  {
    id: 10,
    subject: "데이터베이스",
    professor: "이영구",
    semester: "2024-2",
    author: {
      studentNumber: "20200021",
      userID: "jimin",
    },
    date: "2026-04-28",
    description: "SQL, 트랜잭션, 락 관련 문제 포함.",
    files: ["db-final-lee-2024.pdf"],
  },
  {
    id: 11,
    subject: "컴퓨터네트워크",
    professor: "고한얼",
    semester: "2025-1",
    author: {
      studentNumber: "20230007",
      userID: "harin",
    },
    date: "2026-04-20",
    description: "네트워크 보안 및 응용 계층 중심 문제.",
    files: ["network-final-kim.pdf"],
  },
  {
    id: 12,
    subject: "확률및통계학",
    professor: "김태연",
    semester: "중간고사 모음",
    author: {
      studentNumber: "20220003",
      userID: "yerin",
    },
    date: "2026-04-18",
    description: "최근 3년간 중간고사 기출 모음.",
    files: ["statistics-midterms.zip"],
  },
  {
    id: 13,
    subject: "논리회로",
    professor: "정연모",
    semester: "2024-2",
    author: {
      studentNumber: "20210041",
      userID: "hyunwoo",
    },
    date: "2026-04-04",
    description: "플립플롭, FSM 중심의 기말고사 자료.",
    files: ["logic-final-2024.pdf"],
  },
];
